# fly.toml app configuration file generated for grib on 2024-12-24T20:26:48+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'grib'
primary_region = 'waw'

[build]

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = false
  auto_start_machines = true

[[vm]]
  memory = 512
  cpu_kind = 'shared'
  cpus = 1

[scale]
  count = 1
  idle_timeout = 0

[[mounts]]
  source = 'data'
  destination = '/root/data'
